export type CrmEndpoint =
  | "systemusers"
  | "accounts"
  | "annotations"
  | "connections"
  | "contacts"
  | "dyn_tags"
  | "emailbody"
  | "emails"
  | "ken_services"
  | "ken_customersuccessprojects"
  | "incidents"
  | "templates"
  | "WhoAmI"
  | undefined;
